name = "Default"
description = "Default 8BitDo Micro keyboard layout"

[bindings]
A = ["G"]
B = ["J"]
X = ["H"]
Y = ["I"]
L1 = ["K"]
R1 = ["M"]
L2 = ["L"]
R2 = ["R"]
SELECT = ["N"]
START = ["O"]
HOME = []
LOGO = ["S"]
UP = ["C"]
DOWN = ["D"]
LEFT = ["E"]
RIGHT = ["F"]