name = "Default"

[bindings]
A = ["G"]
B = ["J"]
X = ["H"]
Y = ["I"]
L1 = ["K"]
R1 = ["A"]
L2 = ["L"]
R2 = ["A"]
SELECT = ["N"]
START = ["O"]
HOME = ["NULL"]
LOGO = ["S"]
UP = ["C"]
DOWN = ["D"]
LEFT = ["E"]
RIGHT = ["F"]